const $=id=>document.getElementById(id),NAMES=['Angelica','Anita Salcedo','Anita Suarez','Carol','Daniel','Hector','Nikol','Samuel','Sergio','Yilian'];
const TASKS=[['inicio','ORACIÓN INICIO'],['pan','LECTURA LIBRO "PAN NUESTRO"'],['evangelio','LECTURA EVANGELIO - Fragmento'],['fisica','VIBRACIÓN FÍSICA'],['espiritual','VIBRACIÓN ESPIRITUAL'],['familias','VIBRACIÓN FAMILIAS'],['general','VIBRACIÓN GENERAL'],['final','ORACIÓN FINAL']],IDX=Object.fromEntries(TASKS.map((x,i)=>[x[0],i]));
const KEY='vibraciones_history_v13',BOOKS='vibraciones_books_v13';let state={patient:false,schedule:null,locks:{},manualChapter:false};
const seed={date:'2026-08-12',bookId:'pan',bookName:'Pan Nuestro',chapter:54,chapterTitle:'Razón de los llamados',patient:true,participants:['Angelica','Anita Salcedo','Anita Suarez','Carol','Daniel','Hector','Nikol','Sergio','Yilian'],ordinary:{inicio:'Anita Suarez',pan:'Carol',evangelio:'Nikol',fisica:'Sergio',espiritual:'Anita Salcedo',familias:'Daniel',general:'Yilian',final:'Angelica'},specials:{readingPatients:'Hector',patientWorker:'Yilian',workerVibration:'Nikol',evangelioWithVibration:true}};
function localISO(){const d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)}
function history(){let h=JSON.parse(localStorage.getItem(KEY)||'[]');if(!h.length){h=[seed];localStorage.setItem(KEY,JSON.stringify(h))}return h}function saveHistory(h){localStorage.setItem(KEY,JSON.stringify(h))}
function books(){let b=JSON.parse(localStorage.getItem(BOOKS)||'null');if(!b){b=[{id:'pan',name:'Pan Nuestro',chapters:window.PAN_NUESTRO}];localStorage.setItem(BOOKS,JSON.stringify(b))}return b}function saveBooks(b){localStorage.setItem(BOOKS,JSON.stringify(b))}
function currentBook(){return books().find(x=>x.id===$('book').value)||books()[0]}function prior(){return history().filter(x=>x.date<$('date').value).sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function selected(){return [...document.querySelectorAll('#people input:checked')].map(x=>x.value)}
function progressionOK(name,task){const p=prior();if(!p||!p.participants?.includes(name))return true;const prev=Object.entries(p.ordinary||{}).find(([,n])=>n===name)?.[0];if(!prev)return true;const a=IDX[prev],b=IDX[task];return a===7?b===0:b>a}
function prohibited(name,task){return name==='Anita Suarez'&&task==='pan'||!progressionOK(name,task)}
function candidates(task,used,excluded){return selected().filter(n=>!used.has(n)&&!excluded.has(n)&&!prohibited(n,task)).sort((a,b)=>score(b,task)-score(a,task))}
function score(name,task){const p=prior();if(!p||!p.participants?.includes(name))return 30-IDX[task];const prev=Object.entries(p.ordinary||{}).find(([,n])=>n===name)?.[0];if(!prev)return 20;const a=IDX[prev],b=IDX[task];return a===7&&b===0?100:(b>a?90-(b-a):0)}
function solve(fixed={}){let out={...fixed},used=new Set(Object.values(fixed)),excluded=new Set;const worker=$('worker').value,linked=state.patient&&$('linkEv').checked;if(linked){if(prohibited(worker,'evangelio'))return null;out.evangelio=worker;used.add(worker);excluded.add(worker)}
 const participants=selected();if(state.patient&&!linked&&participants.length>=9)excluded.add(worker);const open=TASKS.map(x=>x[0]).filter(t=>!out[t]);
 function bt(i){if(i===open.length)return true;const t=open[i];for(const n of candidates(t,used,excluded)){out[t]=n;used.add(n);if(bt(i+1))return true;used.delete(n);delete out[t]}return false}return bt(0)?out:null}
function renderPeople(){const p=$('people');p.innerHTML=NAMES.map(n=>`<label class="person"><input type="checkbox" value="${n}" ${n==='Samuel'?'': 'checked'} ${n==='Hector'?'disabled':''}><span class="name">${n}</span>${n==='Anita Suarez'?'<span class="chip">No Pan Nuestro</span>':''}${n==='Hector'?'<span class="chip">Coordinador</span>':''}</label>`).join('');p.querySelectorAll('input:not([disabled])').forEach(x=>x.onchange=()=>{state.schedule=null;renderAdmin()})}
function fillSelects(){const opts=NAMES.filter(n=>n!=='Hector').map(n=>`<option>${n}</option>`).join('');$('patient').innerHTML=opts;$('worker').innerHTML=opts}
function renderBooks(){const b=books();$('book').innerHTML=b.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('book').value=localStorage.getItem('vibraciones_current_book')||'pan';suggestChapter()}
function suggestChapter(){const b=currentBook(),last=history().filter(x=>x.bookId===b.id&&x.date<$('date').value).sort((a,c)=>c.date.localeCompare(a.date))[0];let n=last?Number(last.chapter)+1:54;if(!b.chapters[n])n=1;$('chNo').textContent=n;$('manualNo').value=n;$('bookName').textContent=b.name;$('chTitle').textContent=b.chapters[n]||'';$('manualTitle').value=$('chTitle').textContent}
function chapter(){return Number($('chNo').textContent)}
function generate(){let fixed={...state.locks};if(state.patient&&$('linkEv').checked)fixed.evangelio=$('worker').value;const s=solve(fixed);state.schedule=s;$('programCard').classList.remove('hidden');$('programCard').open=true;if(!s){$('status').className='status warn';$('status').textContent='No existe una combinación completa sin repetir ni retroceder. Cambia una asignación especial, participantes o una tarea manual.';$('program').innerHTML='';renderAdmin();return}$('status').className='status';$('status').textContent='✓ Rotación válida: nadie repite ni retrocede respecto al miércoles anterior.';renderProgram();renderAdmin()}
function renderProgram(){const s=state.schedule;if(!s)return;$('program').innerHTML=TASKS.map(([id,label])=>{const opts=selected().map(n=>`<option ${s[id]===n?'selected':''}>${n}</option>`).join('');return `<div class="row"><div class="task">${label}${id==='pan'?`<small>${currentBook().name} · ${chapter()} · ${$('chTitle').textContent}</small>`:''}</div><select data-task="${id}" ${state.patient&&$('linkEv').checked&&id==='evangelio'?'disabled':''}>${opts}</select></div>`}).join('')+`<div class="row"><div class="task">LECTURA DE PACIENTES</div><div class="responsible">Hector</div></div>${state.patient?`<div class="row"><div class="task">PACIENTE TRABAJADOR GENE</div><div class="responsible">${$('patient').value}</div></div><div class="row"><div class="task">VIBRACIÓN POR TRABAJADOR</div><div class="responsible">${$('worker').value}</div></div>`:''}`;$('program').querySelectorAll('select[data-task]').forEach(el=>el.onchange=()=>{const t=el.dataset.task,n=el.value;if(prohibited(n,t)){alert('Esta asignación no es válida: la persona repetiría o retrocedería respecto al miércoles anterior, o incumple una restricción.');el.value=state.schedule[t];return}state.locks[t]=n})}
function record(draft=true){if(!state.schedule)return null;const b=currentBook();return{date:$('date').value,bookId:b.id,bookName:b.name,chapter:chapter(),chapterTitle:$('chTitle').textContent,patient:state.patient,participants:selected(),ordinary:{...state.schedule},specials:{readingPatients:'Hector',patientWorker:state.patient?$('patient').value:null,workerVibration:state.patient?$('worker').value:null,evangelioWithVibration:state.patient&&$('linkEv').checked},draft}}
function listHTML(r){if(!r)return '<div class="muted">No hay programación disponible.</div>';return TASKS.map(([id,l])=>`<div class="row"><div class="task">${id==='pan'?'LECTURA LIBRO “'+(r.bookName||'Pan Nuestro')+'”':l}${id==='pan'?`<small>${r.chapter} · ${r.chapterTitle||''}</small>`:''}</div><div class="responsible">${r.ordinary?.[id]||'—'}</div></div>`).join('')+`<div class="row"><div class="task">LECTURA DE PACIENTES</div><div class="responsible">Hector</div></div>${r.patient?`<div class="row"><div class="task">PACIENTE TRABAJADOR GENE</div><div class="responsible">${r.specials?.patientWorker||'—'}</div></div><div class="row"><div class="task">VIBRACIÓN POR TRABAJADOR</div><div class="responsible">${r.specials?.workerVibration||'—'}</div></div>`:''}`}
function renderAdmin(){$('admin').innerHTML=listHTML(state.schedule?record():history().find(x=>x.date===$('date').value))}function renderPrevious(){const p=prior();$('previous').innerHTML=p?`<div class="status"><b>${p.date}</b></div>${listHTML(p)}`:'<div class="muted">No hay reunión anterior registrada.</div>'}
const greetings=['Que la paz de Jesús nos acompañe en este encuentro, elevando nuestros pensamientos y fortaleciendo en nosotros la disposición de servir con fraternidad.','Que este encuentro nos ayude a mantener el pensamiento elevado, el corazón sereno y la disposición sincera de servir bajo la orientación del Evangelio de Jesús.','Que la oración y la fraternidad nos reúnan esta noche en un mismo propósito de amor, servicio y renovación espiritual.'];let gi=0;
function makeMessage(){if(!state.schedule)return;const r=record(),lines=[greetings[gi%greetings.length],''];for(const [id,l] of TASKS){const title=id==='pan'?`LECTURA LIBRO "${r.bookName.toUpperCase()}" – ${r.chapter}. ${r.chapterTitle}`:l;lines.push(`*${title}*`,`_${r.ordinary[id]}_`,'')}if(r.patient)lines.splice(8,0,`*PACIENTE TRABAJADOR GENE*`,`_${r.specials.patientWorker}_`,'',`*VIBRACIÓN POR TRABAJADOR*`,`_${r.specials.workerVibration}_`,'');lines.splice(r.patient?17:11,0,'*LECTURA DE PACIENTES*','_Hector_','');lines.push('','*Nos vemos hoy a las 6:55.*','','Bendiciones');$('preview').textContent=lines.join('\n');$('messageCard').classList.remove('hidden');$('messageCard').open=true}
$('pNo').onclick=()=>setPatient(false);$('pYes').onclick=()=>setPatient(true);function setPatient(v){state.patient=v;$('pNo').classList.toggle('active',!v);$('pYes').classList.toggle('active',v);$('patientFields').classList.toggle('hidden',!v);$('linkWrap').classList.toggle('hidden',!v);state.schedule=null;renderAdmin()}
$('generate').onclick=generate;$('reorg').onclick=generate;$('reset').onclick=()=>{state.locks={};generate()};$('makeMsg').onclick=makeMessage;$('greeting').onclick=()=>{gi++;makeMessage()};$('copy').onclick=async()=>{await navigator.clipboard.writeText($('preview').textContent);alert('Mensaje copiado')};$('share').onclick=async()=>{const text=$('preview').textContent;if(navigator.share)await navigator.share({text});else window.open('https://wa.me/?text='+encodeURIComponent(text),'_blank')};$('save').onclick=()=>{if(!state.schedule)return;let h=history(),r=record(false),i=h.findIndex(x=>x.date===r.date);if(i>=0)h[i]=r;else h.push(r);saveHistory(h);alert('Reunión guardada');renderPrevious();renderAdmin();suggestChapter()};
$('date').onchange=()=>{state.schedule=null;state.locks={};suggestChapter();renderPrevious();renderAdmin()};$('book').onchange=()=>{localStorage.setItem('vibraciones_current_book',$('book').value);state.schedule=null;suggestChapter()};$('patient').onchange=$('worker').onchange=$('linkEv').onchange=()=>{state.schedule=null;renderAdmin()};
$('changeChapter').onclick=()=>$('chapterEdit').classList.toggle('hidden');$('manualNo').oninput=()=>{const b=currentBook(),n=Number($('manualNo').value);$('chNo').textContent=n;$('chTitle').textContent=b.chapters[n]||$('manualTitle').value||''};$('manualTitle').oninput=()=>$('chTitle').textContent=$('manualTitle').value;
$('addBook').onclick=()=>$('bookEdit').classList.toggle('hidden');$('saveBook').onclick=()=>{const name=$('newBookName').value.trim(),a=$('newBookChapters').value.split(/\n+/).map(x=>x.trim()).filter(Boolean);if(!name||!a.length)return alert('Escribe nombre y capítulos');const ch={};a.forEach((x,i)=>ch[i+1]=x);let b=books(),id='libro-'+Date.now();b.push({id,name,chapters:ch});saveBooks(b);renderBooks();$('book').value=id;localStorage.setItem('vibraciones_current_book',id);suggestChapter();$('bookEdit').classList.add('hidden')};
$('date').value=localISO();renderPeople();fillSelects();renderBooks();renderPrevious();renderAdmin();if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
