/* v3.0 overrides on top of v2.1 engine */
function refOrd(p){return p?.actualOrdinary||p?.ordinary||{}}
function refSp(p){return p?.actualSpecials||p?.specials||{}}
function oldTask(prev,n){return Object.entries(refOrd(prev)).find(([,v])=>v===n)?.[0]||null}
function oldTaskLabel(prev,n){const t=oldTask(prev,n);return t?(t==='pan'?'Lectura libro':ORDINARY.find(x=>x.id===t)?.label):'Sin actividad ordinaria'}

function migrateV3(){
 const h=history(),date='2026-09-02',i=h.findIndex(x=>x.date===date);
 const rec={date,bookId:'pan-nuestro',bookName:'Pan Nuestro',chapter:57,chapterTitle:'Ante Jesús',participants:['Anita Salcedo','Daniel','Yilian','Samuel','Sergio','Hector','Anita Suarez','Carol','Nikol','Angelica'],ordinary:{inicio:'Anita Salcedo',pan:'Daniel',evangelio:'Yilian',fisica:'Hector',espiritual:'Anita Suarez',familias:'Carol',general:'Nikol',final:'Angelica'},specials:{patientWorker:'Samuel',workerVibration:'Sergio',readingPatients:'Yilian',evangelioWithVibration:false},actualOrdinary:{inicio:'Anita Salcedo',pan:'Daniel',evangelio:'Yilian',fisica:'Hector',espiritual:'Anita Suarez',familias:'Carol',general:'Nikol',final:'Angelica'},actualSpecials:{patientWorker:'Samuel',workerVibration:'Sergio',readingPatients:'Yilian',evangelioWithVibration:false},resting:[]};
 if(i<0)h.push(rec);else h[i]={...h[i],...rec};h.sort((a,b)=>a.date.localeCompare(b.date));saveHistory(h)
}

function populateChapterSelect(){const b=currentBook(),a=Object.entries(b.chapters||{}).sort((x,y)=>+x[0]-+y[0]);$('chapterSelect').innerHTML=a.map(([n,t])=>`<option value="${n}">${n} · ${t}</option>`).join('');$('chapterSelect').value=String($('chNo').textContent)}
function updateChapter(){const b=currentBook();if(!b)return;let no=1;const p=history().filter(x=>x.date<$('date').value&&x.bookId===b.id).sort((a,b)=>a.date.localeCompare(b.date)).at(-1);if(p)no=(+p.chapter||0)+1;if(state.chapterOverride!=null)no=+state.chapterOverride;const title=b.chapters?.[String(no)]||b.chapters?.[no]||`Capítulo ${no}`;$('chNo').textContent=no;$('bookName').textContent=b.name;$('chTitle').textContent=title;$('manualNo').value=no;$('manualTitle').value=title;populateChapterSelect()}

function refreshSpecials(){const list=selected(),po=$('patient')?.value,wo=$('worker')?.value;for(const id of ['patient','worker']){const el=$(id);if(!el)return;el.innerHTML=list.map(n=>`<option>${n}</option>`).join('');if(id==='patient'&&list.includes(po))el.value=po;else if(id==='worker'&&list.includes(wo))el.value=wo;else if(id==='patient'&&list.includes('Samuel'))el.value='Samuel';else if(id==='worker'&&list.includes('Nikol'))el.value='Nikol'}syncWorkerRule();renderPatientOptions()}
function renderPatientOptions(){const w=$('patientExtraWrap');if(!state.hasPatient){w.classList.add('hidden');return}w.classList.remove('hidden');$('patientAllowed').classList.toggle('hidden',!$('patientExtra').checked);if(!$('patientAllowedList').children.length)$('patientAllowedList').innerHTML=ORDINARY.map(t=>`<label><input type="checkbox" value="${t.id}" ${['inicio','pan','evangelio','final'].includes(t.id)?'checked':''}><span>${t.id==='pan'?'Lectura libro':t.label}</span></label>`).join('')}
function patientAllowed(){return $('patientExtra').checked?[...document.querySelectorAll('#patientAllowedList input:checked')].map(x=>x.value):[]}

function chooseOrdinaryPeople(prev){let names=selected().filter(n=>n!=='Hector'),q=restQueue(),ret=q.filter(n=>names.includes(n)),newc=names.filter(n=>!oldTask(prev,n));state.resting=[];state.reentered=ret.slice();state.specialOnly=[];if(state.hasPatient){const p=$('patient').value,w=$('worker').value,linked=$('linkEv').checked&&w!=='Hector';if(!$('patientExtra').checked&&p!=='Hector'&&names.includes(p)){names=names.filter(n=>n!==p);state.specialOnly.push(p)}if(!linked&&w!=='Hector'&&names.length>8&&names.includes(w)){names=names.filter(n=>n!==w);state.specialOnly.push(w)}}while(names.length>8){let r=null,f=refOrd(prev)?.final;if(f&&names.includes(f)&&!ret.includes(f)&&!newc.includes(f))r=f;if(!r)r=names.find(n=>!ret.includes(n)&&!newc.includes(n))||names.at(-1);names=names.filter(n=>n!==r);state.resting.push(r)}return names}
function solve(prev,names,shift,fixed){let pool=names.slice(),fn=Object.values(fixed);if((pool.length<8||fn.includes('Hector'))&&!pool.includes('Hector'))pool.push('Hector');if(pool.length<8)return null;const old={};for(const n of pool)old[n]=oldTask(prev,n);function allowed(n,t){if(person(n).noPan&&t==='pan')return false;if(fixed[t]&&fixed[t]!==n)return false;for(const [ft,x] of Object.entries(fixed))if(x===n&&ft!==t)return false;if(n==='Hector'&&!fn.includes('Hector')&&names.length>=8)return false;if(state.hasPatient&&n===$('patient').value&&$('patientExtra').checked&&!patientAllowed().includes(t))return false;const o=old[n];if(!o)return true;if(fixed[t]===n)return true;const d=dist(o,t);return d>=shift&&d>0}function score(n,t){const o=old[n];if(!o)return 20-idx(t)/100;const d=dist(o,t);return d===shift?200:120-(d-shift)*12}const as={},used=new Set();for(const [t,n] of Object.entries(fixed)){if(!pool.includes(n)||!allowed(n,t))return null;as[t]=n;used.add(n)}const open=ORDINARY.map(x=>x.id).filter(t=>!as[t]);let best=null,bs=-1e9;function rec(i,s){if(i===open.length){if(s>bs){bs=s;best={...as}}return}const t=open[i];for(const n of pool){if(used.has(n)||!allowed(n,t))continue;used.add(n);as[t]=n;rec(i+1,s+score(n,t));delete as[t];used.delete(n)}}rec(0,0);return best}

function renderProgram(){$('programCard').classList.remove('hidden');const err=validate();$('errorBox').textContent=err;$('errorBox').classList.toggle('hidden',!err);if(!state.schedule){$('program').innerHTML='';return}const opts=selected(),p=prevMeeting();$('program').innerHTML=ORDINARY.map(t=>{const n=state.schedule[t.id];return `<div class="row"><div class="task">${taskLabel(t.id)}<small>Anterior de ${n}: ${oldTaskLabel(p,n)}</small></div><select data-task="${t.id}">${opts.map(x=>`<option ${n===x?'selected':''}>${x}</option>`).join('')}</select></div>`}).join('')+specialRows();document.querySelectorAll('#program select[data-task]').forEach(s=>s.onchange=()=>state.locks[s.dataset.task]=s.value)}
function renderPrevious(){const p=prevMeeting();if(!p){$('previous').innerHTML='<span class="muted">No hay reunión anterior.</span>';return}const o=refOrd(p),s=refSp(p),book=p.bookName||'Pan Nuestro',ct=p.chapterTitle||window.PAN_NUESTRO?.[p.chapter]||`Capítulo ${p.chapter}`,r=[['ORACIÓN INICIO',o.inicio],[`LECTURA LIBRO “${book.toUpperCase()}” – ${p.chapter}. ${ct}`,o.pan],['LECTURA EVANGELIO - Fragmento',o.evangelio]];if(s.patientWorker)r.push(['PACIENTE TRABAJADOR GENE',s.patientWorker],['VIBRACIÓN POR TRABAJADOR',s.workerVibration]);r.push(['LECTURA DE PACIENTES',s.readingPatients||'Hector']);for(const t of ['fisica','espiritual','familias','general','final'])r.push([ORDINARY.find(x=>x.id===t).label,o[t]]);$('previous').innerHTML=`<div class="muted" style="margin-bottom:7px">${p.date}</div>`+r.filter(x=>x[1]).map(([t,n])=>`<div class="row"><div class="task">${t}</div><div class="responsible">${n}</div></div>`).join('')}

function renderActual(){const h=$('actual'),rec=history().find(x=>x.date===$('date').value),base=rec?.actualOrdinary||rec?.ordinary||state.schedule;if(!base){h.innerHTML='<div class="muted" style="margin-top:8px">Primero guarda la programación del miércoles.</div>';return}const opts=selected();let x=ORDINARY.map(t=>`<div class="row"><div class="task">${taskLabel(t.id)}</div><select data-actual="${t.id}">${opts.map(n=>`<option ${base[t.id]===n?'selected':''}>${n}</option>`).join('')}</select></div>`).join(''),sp=rec?.actualSpecials||rec?.specials||{};if(sp.patientWorker)x+=`<div class="row"><div class="task">PACIENTE TRABAJADOR GENE</div><select id="actualPatient">${opts.map(n=>`<option ${sp.patientWorker===n?'selected':''}>${n}</option>`).join('')}</select></div><div class="row"><div class="task">VIBRACIÓN POR TRABAJADOR</div><select id="actualWorker">${opts.map(n=>`<option ${sp.workerVibration===n?'selected':''}>${n}</option>`).join('')}</select></div>`;x+=`<div class="row"><div class="task">LECTURA DE PACIENTES</div><select id="actualRead">${opts.map(n=>`<option ${(sp.readingPatients||'Hector')===n?'selected':''}>${n}</option>`).join('')}</select></div>`;h.innerHTML=x}
function saveActual(){const h=history(),i=h.findIndex(x=>x.date===$('date').value);if(i<0)return alert('Primero guarda la programación.');const o={};document.querySelectorAll('[data-actual]').forEach(s=>o[s.dataset.actual]=s.value);h[i].actualOrdinary=o;h[i].actualSpecials={patientWorker:$('actualPatient')?.value||null,workerVibration:$('actualWorker')?.value||null,readingPatients:$('actualRead')?.value||'Hector',evangelioWithVibration:h[i].specials?.evangelioWithVibration||false};saveHistory(h);renderPrevious();alert('Actividad realizada guardada. La próxima rotación usará este registro.')}

function patchV3(){migrateV3();const sam=[...document.querySelectorAll('#people input')].find(x=>x.value==='Samuel');if(sam)sam.checked=true;refreshSpecials();$('changeChapter').onclick=()=>{$('chapterEdit').classList.toggle('hidden');populateChapterSelect()};$('chapterSelect').onchange=()=>{state.chapterOverride=+$('chapterSelect').value;updateChapter()};$('book').onchange=()=>{state.chapterOverride=null;updateChapter()};$('date').onchange=()=>{state.chapterOverride=null;updateChapter();renderPrevious();renderActual()};$('patient').onchange=renderPatientOptions;$('patientExtra').onchange=renderPatientOptions;$('saveActual').onclick=saveActual;renderPrevious();renderActual()}
document.addEventListener('DOMContentLoaded',patchV3);
